services:
    laravel.test:
        build:
            context: './docker/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '${REVERB_PORT:-8080}:${REVERB_PORT:-8080}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    temporal:
        depends_on:
            - mysql
        environment:
            DB: mysql8
            DB_PORT: 3306
            MYSQL_USER: root
            MYSQL_PWD: '${DB_PASSWORD}'
            MYSQL_SEEDS: mysql
            DYNAMIC_CONFIG_FILE_PATH: 'config/dynamicconfig/development-sql.yaml'
            TEMPORAL_ADDRESS: temporal:7233
            TEMPORAL_CLI_ADDRESS: temporal:7233
        image: temporalio/auto-setup:${TEMPORAL_VERSION}
        networks:
            - sail
        ports:
            - 7233:7233
        volumes:
            - './dynamicconfig:/etc/temporal/config/dynamicconfig'
    temporal-admin-tools:
        depends_on:
            - temporal
        environment:
            TEMPORAL_ADDRESS: temporal:7233
            TEMPORAL_CLI_ADDRESS: temporal:7233
        image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
        networks:
            - sail
        stdin_open: true
        tty: true
    temporal-ui:
        depends_on:
            - temporal
        environment:
            TEMPORAL_ADDRESS: temporal:7233
            TEMPORAL_CORS_ORIGINS: http://localhost:3000
        image: temporalio/ui:${TEMPORAL_UI_VERSION}
        networks:
            - sail
        ports:
            - 8081:8080
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
